imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    nodes:
        my-tests:
            environment:
                php:
                    version: 8.1
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    tests:
        override:
            -
                # command: "composer phpunit"
                command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"
